# Set the hostnames of the machines you want to use. These must match entries in
# your ssh config file. You should also ensure that these entries are configured
# to use an IdentityFile pointing to an ssh key without password. Note that SSH
# Agent is not supported.
#
# Example of an .ssh/config file entry defining the host named `host_a`:
#
# Host host_a
#    HostName host1.example.com
#    User user
#    IdentityFile ~/.ssh/id_rsa
#
[hosts]
switch_dut = ""
switch_tg  = ""
pktgen     = ""
server     = ""

# Set the paths to this repo on the remote machines.
# Ensure that the user you are using to ssh into the machines has write access
# to these directories. This user is set in the .ssh/config file (see above).
[repo]
switch_dut = ""
switch_tg  = ""
pktgen     = ""
server     = ""

[devices.switch_dut]
sde            = ""   # Path to SDE dir
tofino_version = 2    # TNA versions 1 or 2
ports          = [  ] # Active ports on the switch.

[devices.switch_tg]
sde            = ""   # Path to SDE dir.
tofino_version = 1    # TNA versions 1 or 2.
ports          = [  ] # Active ports on the switch.
pktgen_port    = 0    # Pktgen sends traffic to this port.

[devices.pktgen]
tx_dev       = ""
rx_dev       = ""
tx_line_rate = 100 # in Gbps.
nb_tx_cores  = 4

[devices.server]
dev = ""

[logs]
# Log files. They will be saved in the orchestrator machine in the same
# directory where you run the experiment.py script.
controller_dut = "logs/controller_dut.log"
switch_dut     = "logs/switch_dut.log"
controller_tg  = "logs/controller_tg.log"
switch_tg      = "logs/switch_tg.log"
pktgen         = "logs/pktgen.log"
server         = "logs/server.log"
experiment     = "logs/experiment.log"

[extra]
dpdk_mem_channels = 4
