# Set the hostnames of the machines you want to use. These must match entries in
# your ssh config file. You should also ensure that these entries are configured
# to use an IdentityFile pointing to an ssh key without password. Note that SSH
# Agent is not supported.
#
# Example of an .ssh/config file entry defining the host named `host_a`:
#
# Host host_a
#    HostName host1.example.com
#    User user
#    IdentityFile ~/.ssh/id_rsa
#
[hosts]
switch = ""
pktgen = ""


# Set the paths to this repo on the remote machines.
# Ensure that the user you are using to ssh into the machines has write access
# to these directories. This user is set in the .ssh/config file (see above).
[repo]
switch = ""
pktgen = ""


[devices.switch]
sde = ""                 # Path to SDE dir
tofino_version = 1       # TNA versions 1 or 2
pktgen_inbound_port = 0  # Pktgen sends traffic to this port.
pktgen_outbound_port = 0 # Port that connects to the RX pktgen device.


[devices.pktgen]
tx_dev = ""
rx_dev = ""
tx_line_rate = -1 # in Gbps.
nb_tx_cores = -1


[logs]
# Log files. They will be saved in the orchestrator machine in the same
# directory where you run the experiment.py script.
controller = ""
switch = ""
pktgen = ""


[extra]
dpdk_mem_channels = 4
