[switch]
model = "Wedge 100B-32X"

########################################################
#                   Front panel ports                  #
########################################################

[[switch.front_panel_ports]]
dev = 0
capacity_bps = 100_000_000_000 # 100G

[[switch.front_panel_ports]]
dev = 1
capacity_bps = 100_000_000_000 # 100G

[[switch.front_panel_ports]]
dev = 2
capacity_bps = 100_000_000_000 # 100G

########################################################
#                 Recirculation ports                  #
########################################################

[[switch.recirculation_ports]]
dev = 0
capacity_bps = 125_000_000_000 # 125G

[[switch.recirculation_ports]]
dev = 1
capacity_bps = 125_000_000_000 # 125G

########################################################
#                     Architecture                     #
########################################################

[switch.arch]
name = "Tofino"
max_packet_bytes_in_condition = 4
pipes = 2
stages = 12
sram_per_stage = 10485760                       # 128 * 1024 * 80 bits
tcam_per_stage = 540672                         # 44 * 512 * 24 bits
map_ram_per_stage = 6291456                     # 128 * 1024 * 48 bits
max_logical_tcam_tables_per_stage = 8
max_logical_sram_and_tcam_tables_per_stage = 16
phv_size = 4000                                 # bits
phv_8bit_containers = 64
phv_16bit_containers = 96
phv_32bit_containers = 64
packet_buffer_size = 160000000                  # 20e6 * 8 bits
exact_match_xbar_per_stage = 1024               # 128 * 8 bits
max_exact_match_keys = 16
ternary_match_xbar = 528                        # 66 * 8 bits
max_ternary_match_keys = 8
max_salu_size = 32                              # bits

[controller]
capacity_pps = 100_000 # pps

[x86]
capacity_pps = 120_000_000 # pps
